name: Build and Test project

on:
  pull_request:
    types:
      - opened
    paths:
      - 'Assets/**'
      - 'Packages/**'
  workflow_dispatch: {}

jobs:

    buildForAllSupportedPlatforms:
        name: Build for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64 # Build a Windows 64-bit standalone.
        steps:
            - uses: actions/checkout@v2
              with:
                  fetch-depth: 0
                  lfs: true
            - uses: actions/cache@v2
              with:
                  path: Library
                  key: Library-${{ matrix.targetPlatform }}
                  restore-keys: Library-
            - uses: game-ci/unity-builder@v2
              env:
                  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                  UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                  UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                  targetPlatform: ${{ matrix.targetPlatform }}
            - uses: actions/upload-artifact@v2
              with:
                  name: Build-${{ matrix.targetPlatform }}
                  path: build/${{ matrix.targetPlatform }}

    testForAllSupportedPlatforms:
        name: Test for ${{ matrix.targetPlatform }}
        runs-on: ubuntu-latest
        strategy:
            fail-fast: false
            matrix:
                targetPlatform:
                    - StandaloneWindows64 # Builds on Windows 64-bit standalone.
        steps:
            - uses: game-ci/unity-test-runner@v2
              env:
                UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
                UNITY_EMAIL: ${{ secrets.UNITY_EMAIL }}
                UNITY_PASSWORD: ${{ secrets.UNITY_PASSWORD }}
              with:
                githubToken: ${{ secrets.GITHUB_TOKEN }}
                projectPath: ${GITHUB_WORKSPACE}
